version: "3"

services:
#  frontend:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
#    volumes:
#      - ./api/src/:/usr/code/src/ # Mounts the local 'src' directory into the container at '/app/src'
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
#    env_file:
#      - .env
    environment:
      - MYSQL_DATABASE=sketch_guess
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=localhost
      - MYSQL_USER=gleb
      - MYSQL_PASSWORD=new_pass
    volumes:
      - ./api/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql